version: "3.8"
services:
  product-service:
    image: product-service
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always