spring:
  application:
    name: product
  datasource:
    url: jdbc:h2:file:c:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop
  h2:
    console.enabled: true

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          -health
          -info
          -metrics
          -prometheus
